#!/usr/bin/env python
import sys, os, time
import tweepy
keys = dict(
consumer_key= 9Dt2LIPqEo04QQCL7kPxoqAhJ ,
consumer_secret= jzE88V4Rp6dTQIHLcnmlprgjkZTbh2lqBPtGCYK5ozHgWTJDRr ,
access_token= 1081759204803837952-ObpLpzR9L5wpkcvol5PIJZomTFK8SC , 
access_token_secret= wV1TVjntkorVz5YaigLxDQLAuN5J9fMTTv8cBvedg0ZP2
)

user = @tomlincados

auth = tweepy.OAuthHandler(keys[9Dt2LIPqEo04QQCL7kPxoqAhJ], keys[jzE88V4Rp6dTQIHLcnmlprgjkZTbh2lqBPtGCYK5ozHgWTJDRr])
auth.set_access_token(keys[1081759204803837952-ObpLpzR9L5wpkcvol5PIJZomTFK8SC], keys[wV1TVjntkorVz5YaigLxDQLAuN5J9fMTTv8cBvedg0ZP2])
api = tweepy.API(auth)

def tweet():
	message=input(y’all still tweeting from iphones and androids lmao couldn’t be me)
	api.update_status(message)
	time.sleep(1000)
if __name__ == "__main__":
	while 1:
		tweet()
